### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by openainext** [STUkh/generator-angular-webpack-es6#15]
Uncaught ReferenceError: exports is not defined

**Comment by DesignByMax** [comment]
Do we need to version lock the webpack (or other packages) to fix the above issue? Probably, yes for now.

**Comment by STUkh** [comment]
Thank you for your feedback. Seems that error in webpack 2.2.0-rc.4, so i locked in 2.2.0-rc.3, also added necessary postcss config file and fix small jquery import error in generator.
Fixed in 0.5.0

**Comment by nmccready** [comment]
@STUkh this is still a problem in the latest webpack 2.2.1 any ideas?

**Comment by STUkh** [comment]
Look into this issue
https://github.com/webpack/webpack/issues/3917

You can also try remove add-module-exports plug-in and all require statements replace with imports. Please, reply here if it works
